### ISSUE TITLE
Getting Reference Error: ProgressView not defined.

### ISSUE THREAD

**Issue by syeddanishali8080** [sidneys/cordova-plugin-progressview#6]
Here is how I'm trying to use this plugin:

```
     ProgressView.show("This","CIRCLE","HOLO_LIGHT");
```

But getting reference error whenever I try to do this. can you please tell me why I am getting this error.
The error is here:

 ReferenceError: ProgressView is not defined
    at Scope.$scope.showLoading (http://192.168.1.115:8100/js/MainScreenCtrl.js:
205:11)
    at fn (eval at <anonymous> (http://192.168.1.115:8100/lib/ionic/js/ionic.bun
dle.js:1:0), <anonymous>:4:232)
    at http://192.168.3.115:8100/lib/ionic/js/ionic.bundle.js:62386:9
    at Scope.$eval (http://192.168.1.115:8100/lib/ionic/js/ionic.bundle.js:29158
:28)
    at Scope.$apply (http://192.168.1.115:8100/lib/ionic/js/ionic.bundle.js:2925
7:23)
    at HTMLButtonElement.<anonymous> (http://192.168.1.115:8100/lib/ionic/js/ion
ic.bundle.js:62385:13)
    at HTMLButtonElement.eventHandler (http://192.168.1.115:8100/lib/ionic/js/io
nic.bundle.js:16583:21)
    at triggerMouseEvent (http://192.168.1.115:8100/lib/ionic/js/ionic.bundle.js
:2948:7)
    at tapClick (http://192.168.1.115:8100/lib/ionic/js/ionic.bundle.js:2937:3)
    at HTMLDocument.tapTouchEnd (http://192.168.1.115:8100/lib/ionic/js/ionic.bu
ndle.js:3064:5)

**Comment by moshiki** [comment]
Had the same issue and finally got it working!

Here is how I did it:

1. Installed the plugin from kartagis's fork: 
    `cordova plugin add https://github.com/kartagis/cordova-plugin-progressview.git`

2. Adressed the plugin with:
    `window.plugins.ProgressView.show("text...", "HORIZONTAL");`
